# Generated by Django 4.1 on 2022-09-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(default='', max_length=200)),
                ('creator', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('issue_title', models.CharField(default='', max_length=200)),
                ('issue_description', models.CharField(default='', max_length=200)),
                ('project_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapp.project')),
            ],
        ),
    ]
