# Generated by Django 4.1 on 2022-09-02 05:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dapp', '0002_remove_issue_issue_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project_title',
        ),
    ]
