# Generated by Django 4.1 on 2022-09-02 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dapp', '0003_remove_issue_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project_title',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                    to='dapp.project'),
            preserve_default=False,
        ),
    ]
