# Generated by Django 4.1 on 2022-09-02 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dapp', '0005_issuereporter_issueassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereporter',
            name='issue_id',
        ),
        migrations.DeleteModel(
            name='IssueAssign',
        ),
        migrations.DeleteModel(
            name='IssueReporter',
        ),
    ]
