# Generated by Django 4.1 on 2022-09-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dapp', '0006_remove_issuereporter_issue_id_delete_issueassign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(default='', max_length=200)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redata',
                                               to='dapp.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(default='', max_length=200)),
                ('issue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asdata',
                                               to='dapp.issue')),
            ],
        ),
    ]
